### ISSUE TITLE
[Dev] SigningServer.Client error handling not working if server connection succeeds

### ISSUE THREAD

**Issue by sphr2k** [Danielku15/SigningServer#20]
I tried out the Dev branch and noticed that the client will report that the sign request succeeded, even if it didn't, e.g. due to an auth failure.

Server & Client logs (from the same sign request):

[Server.txt](https://github.com/Danielku15/SigningServer/files/8680649/Server.txt)
[Client.txt](https://github.com/Danielku15/SigningServer/files/8680650/Client.txt)

Server & Client config (wrong password in client config is intentional to demonstrate the issue):

[config.json.txt](https://github.com/Danielku15/SigningServer/files/8680670/config.json.txt)
[appsettings.json.txt](https://github.com/Danielku15/SigningServer/files/8680671/appsettings.json.txt)

Best regards

**Comment by Danielku15** [comment]
Thanks for reporting. From the code in a first glance the error handling seems correct. Likely something on the multipart-data serialization gets messed up for the status. Or the exception is swallowed away. Will have a look
