### ISSUE TITLE
Add API to write Certificate into a local file

### ISSUE THREAD

**Issue by Danielku15** [Danielku15/SigningServer#26]
As a counterpart of https://github.com/Danielku15/SigningServer/pull/21 where signatures can be generated, also the certificate (public key) is needed to have a fully automated workflow where signing and verification can be integrated well.

**Comment by RAMAMario** [comment]
Follow-up note: To be able to verify the certificate itself and its' chain with the root ca and intermediate ca it would be nice to not only have the leaf certificate but also the root and intermediate available similar to what you would get in a signed windows executable.
