### ISSUE TITLE
Android AAB signing fails: Signing Failed with error 'Failed to determine APK's minimum supported Android platform version'

### ISSUE THREAD

**Issue by nullPtrsEverywhere** [Danielku15/SigningServer#34]
Signing Failed with error 'Failed to determine APK's minimum supported Android platform version' when trying to sign an AAB (APK signs normally)

AAB build info:
 - targetSdkVersion="33"
 - minSdkVersion="29"
 - Android SDK Buld tools v 32 used

Some people had similar issues and they just used the hack (not really a solution) :
C:\Android\build-tools\30.0.3\apksigner.bat sign --ks my-release-key.jks --out signed.aab --min-sdk-version 14 TestAligned.aab
(I had to add the "--min-sdk-version 14" to fix the error: "Failed to determine APK's minimum supported platform version.")"

**Comment by Danielku15** [comment]
Can you provide the example file you are having? In our tests we have the full APK unit test suite of the official apksigner. The fact that you also had to add `--min-sdk-version` pinpoints the issue. 

At this point you cannot specify such format signing specific options when using SigningServer and I could add such a feature. But to solve your problem today you could just add the right attribute to your ApplicationManifest.xml of your package hinted in the docs

![image](https://github.com/Danielku15/SigningServer/assets/674916/2ec79b7b-1d3f-421f-9a27-ba25b435beae)
(https://developer.android.com/tools/apksigner)

**Comment by nullPtrsEverywhere** [comment]
As stated above, our AndroidManifest.xml already has the minSdkVersion property there:
![image](https://github.com/Danielku15/SigningServer/assets/96131973/de0ca96c-2611-43e5-b929-1ad4bda553de)

When I sign the aab with this command locally there are no signing issues:
"jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -storepass alias_name -keystore my-key.keystore test.aab alias_name"

The "--min-sdk-version" is from a bit of googling the error above.

**Comment by Danielku15** [comment]
Interesting finding which changes the topic quite a lot. I wasn't ware that AABs are different from APKs. In this case the workaround until a full fix could be: 

* Rename the file to `.jar` before signing and then rename it back to `.aab`

SigningServer uses the file extension to determine which signing to use and currently we have `.aab` configured to use the android signing mode. Renaming it to `.jar` will ensure only the classical JAR signing (equal to V1 signing scheme) is used.

References: 
- https://stackoverflow.com/questions/63290907/if-i-sign-an-aab-with-jarsigner-do-i-need-to-sign-the-apks-and-also-the-resulti
